build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
args:
  BDS_VERSION: "1.21.132.3"
  BDS_URL: "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.132.3.zip"
  EASY_ADD_VERSION: "0.8.11"
  ENTRYPOINT_DEMOTER_VERSION: "0.4.9"
  SET_PROPERTY_VERSION: "0.1.5"
  RESTIFY_VERSION: "1.7.11"
  MC_MONITOR_VERSION: "0.16.0"
labels:
  org.opencontainers.image.title: "Minecraft Bedrock Beta (HA Add-on)"
  org.opencontainers.image.description: "Bedrock server gebundeld"
