build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
args:
  BDS_VERSION: "1.21.123.2"
  BDS_URL: "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.123.2.zip"
  EASY_ADD_VERSION: "0.8.10"
  ENTRYPOINT_DEMOTER_VERSION: "0.4.8"
  SET_PROPERTY_VERSION: "0.1.4"
  RESTIFY_VERSION: "1.7.10"
  MC_MONITOR_VERSION: "0.15.7"
labels:
  org.opencontainers.image.title: "Minecraft Bedrock Beta (HA Add-on)"
  org.opencontainers.image.description: "Bedrock server gebundeld"
