build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  armv7: ghcr.io/home-assistant/armv7-base-debian:trixie

args:
  BDS_VERSION: "1.21.121"
  BDS_URL: "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.121.1.zip"
  EASY_ADD_VERSION: "0.8.11"
  ENTRYPOINT_DEMOTER_VERSION: "0.4.0"
  SET_PROPERTY_VERSION: "0.1.1"
  RESTIFY_VERSION: "1.6.1"
  MC_MONITOR_VERSION: "0.5.0"

labels:
  org.opencontainers.image.title: "Minecraft Bedrock Beta (HA Add-on)"
  org.opencontainers.image.description: "Bedrock server gebundeld"
